import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="acid">
      <body className={`${inter.className} min-h-screen w-5/6 m-auto`}>
        <header>
          <div className="flex flex-rows px-5 mx-auto mt-8 mb-8 h-16 justify-between items-center rounded-2xl text-4xl font-bold bg-purple-600 ">
            <p className="text-white"> XCTUALITY</p>
            <div className="w-10">
              <Image
                src="/assets/menu.png"
                width="512"
                height="512"
                alt=""
                className="w-full h-full object-cover cursor-pointer"
              />
            </div>
          </div>
        </header>
        <main className="flex-col mb-24">{children}</main>
      </body>
    </html>
  );
}
